#!/usr/bin/env bash

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
find -mindepth 1 -maxdepth 1 -name '.tmp.*' -type d -execdir rm -r '{}' +
./dbd.py &
python3 ./index.py 12321 --cgi &
xdg-open http://localhost:12321/cgi-bin/index
wait
